alter table "public"."orders" drop constraint "orders_product_id_fkey";

alter table "public"."orders" drop constraint "orders_transaction_no_fkey";

alter table "public"."products" drop constraint "products_category_id_fkey";

alter table "public"."sales" drop constraint "sales_transaction_no_fkey";

create table "public"."logs" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "action" character varying not null,
    "description" text
);


create table "public"."reorder_products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default gen_random_uuid(),
    "product_id" uuid not null,
    "qty" integer not null,
    "comment" text
);


create table "public"."suppliers" (
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "contact_person" character varying,
    "address" character varying,
    "contact_no" character varying,
    "user_id" uuid,
    "id" uuid default gen_random_uuid()
);


alter table "public"."products" add column "uom" character varying;

alter table "public"."products" add column "volume" integer;

alter table "public"."products" add column "weight" integer;

CREATE UNIQUE INDEX logs_pkey ON public.logs USING btree (id);

CREATE UNIQUE INDEX products_name_key ON public.products USING btree (name);

CREATE UNIQUE INDEX reorder_products_pkey ON public.reorder_products USING btree (id);

CREATE UNIQUE INDEX suppliers_name_key ON public.suppliers USING btree (name);

alter table "public"."logs" add constraint "logs_pkey" PRIMARY KEY using index "logs_pkey";

alter table "public"."reorder_products" add constraint "reorder_products_pkey" PRIMARY KEY using index "reorder_products_pkey";

alter table "public"."logs" add constraint "logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."logs" validate constraint "logs_user_id_fkey";

alter table "public"."products" add constraint "products_name_key" UNIQUE using index "products_name_key";

alter table "public"."reorder_products" add constraint "reorder_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."reorder_products" validate constraint "reorder_products_product_id_fkey";

alter table "public"."reorder_products" add constraint "reorder_products_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."reorder_products" validate constraint "reorder_products_user_id_fkey";

alter table "public"."suppliers" add constraint "suppliers_name_key" UNIQUE using index "suppliers_name_key";

alter table "public"."suppliers" add constraint "suppliers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."suppliers" validate constraint "suppliers_user_id_fkey";

alter table "public"."orders" add constraint "orders_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) not valid;

alter table "public"."orders" validate constraint "orders_product_id_fkey";

alter table "public"."orders" add constraint "orders_transaction_no_fkey" FOREIGN KEY (transaction_no) REFERENCES transactions(transaction_no) not valid;

alter table "public"."orders" validate constraint "orders_transaction_no_fkey";

alter table "public"."products" add constraint "products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."products" validate constraint "products_category_id_fkey";

alter table "public"."sales" add constraint "sales_transaction_no_fkey" FOREIGN KEY (transaction_no) REFERENCES transactions(transaction_no) not valid;

alter table "public"."sales" validate constraint "sales_transaction_no_fkey";

grant delete on table "public"."logs" to "anon";

grant insert on table "public"."logs" to "anon";

grant references on table "public"."logs" to "anon";

grant select on table "public"."logs" to "anon";

grant trigger on table "public"."logs" to "anon";

grant truncate on table "public"."logs" to "anon";

grant update on table "public"."logs" to "anon";

grant delete on table "public"."logs" to "authenticated";

grant insert on table "public"."logs" to "authenticated";

grant references on table "public"."logs" to "authenticated";

grant select on table "public"."logs" to "authenticated";

grant trigger on table "public"."logs" to "authenticated";

grant truncate on table "public"."logs" to "authenticated";

grant update on table "public"."logs" to "authenticated";

grant delete on table "public"."logs" to "service_role";

grant insert on table "public"."logs" to "service_role";

grant references on table "public"."logs" to "service_role";

grant select on table "public"."logs" to "service_role";

grant trigger on table "public"."logs" to "service_role";

grant truncate on table "public"."logs" to "service_role";

grant update on table "public"."logs" to "service_role";

grant delete on table "public"."reorder_products" to "anon";

grant insert on table "public"."reorder_products" to "anon";

grant references on table "public"."reorder_products" to "anon";

grant select on table "public"."reorder_products" to "anon";

grant trigger on table "public"."reorder_products" to "anon";

grant truncate on table "public"."reorder_products" to "anon";

grant update on table "public"."reorder_products" to "anon";

grant delete on table "public"."reorder_products" to "authenticated";

grant insert on table "public"."reorder_products" to "authenticated";

grant references on table "public"."reorder_products" to "authenticated";

grant select on table "public"."reorder_products" to "authenticated";

grant trigger on table "public"."reorder_products" to "authenticated";

grant truncate on table "public"."reorder_products" to "authenticated";

grant update on table "public"."reorder_products" to "authenticated";

grant delete on table "public"."reorder_products" to "service_role";

grant insert on table "public"."reorder_products" to "service_role";

grant references on table "public"."reorder_products" to "service_role";

grant select on table "public"."reorder_products" to "service_role";

grant trigger on table "public"."reorder_products" to "service_role";

grant truncate on table "public"."reorder_products" to "service_role";

grant update on table "public"."reorder_products" to "service_role";

grant delete on table "public"."suppliers" to "anon";

grant insert on table "public"."suppliers" to "anon";

grant references on table "public"."suppliers" to "anon";

grant select on table "public"."suppliers" to "anon";

grant trigger on table "public"."suppliers" to "anon";

grant truncate on table "public"."suppliers" to "anon";

grant update on table "public"."suppliers" to "anon";

grant delete on table "public"."suppliers" to "authenticated";

grant insert on table "public"."suppliers" to "authenticated";

grant references on table "public"."suppliers" to "authenticated";

grant select on table "public"."suppliers" to "authenticated";

grant trigger on table "public"."suppliers" to "authenticated";

grant truncate on table "public"."suppliers" to "authenticated";

grant update on table "public"."suppliers" to "authenticated";

grant delete on table "public"."suppliers" to "service_role";

grant insert on table "public"."suppliers" to "service_role";

grant references on table "public"."suppliers" to "service_role";

grant select on table "public"."suppliers" to "service_role";

grant trigger on table "public"."suppliers" to "service_role";

grant truncate on table "public"."suppliers" to "service_role";

grant update on table "public"."suppliers" to "service_role";


